### PR TITLE
added get previous/next day method

### PR DESCRIPTION
**Pull request by RoshanDalami**
### Issue Reference
Issue Reference #16 

### Proposed Changes
Added method.
.getPreviousDay()
.getNextDay()

### Checklist

- [ ] Lint rules are passed correctly
- [ ] Code builds correctly
- [ ] Created or updated tests for the new code
- [ ] All existing and new tests passed
- [ ] Pull request title is concise and descriptive.
- [ ] Pull request is linked to the related issue.

### CODE REVIEW

**Review by blackkspydo — CHANGES_REQUESTED** [review]
- `getPreviousDay`: Get the Bikram Sambat date of the previous day from a given date.
- `getNextDay`: Get the Bikram Sambat date of the next day from a given date.

**Comment by RoshanDalami** [comment]
date like 23/08/2023 ?

**Comment by blackkspydo** [comment]
> date like 23/08/2023 ?

For now just return an instance of BS date. 
you can use .addDays() method, do not modify the current object but return a new one

**Comment by RoshanDalami** [comment]
So , I simply need to return 'this.addDays(-1) ' and 'this.addDays(1)'

**Comment by blackkspydo** [comment]
> So , I simply need to return 'this.addDays(-1) ' and 'this.addDays(1)'

addDays() is a mutable methos which means it will change current object too, .getNextDay is supposed to be immutable method. so 
create new Object with this instance
```javascript
const currentDate = new BikramSambat(this)
return currentDate.addDays(1)
```

**Comment by RoshanDalami** [comment]
This will do . 

Screenshot 2023-08-25 at 21 48 08

**Comment by blackkspydo** [comment]
> This will do .
> Screenshot 2023-08-25 at 21 48 08

lgtm, dont forget to fix prettier formatting

**Pull request closed without merging**
